### ISSUE TITLE
build failed with cross compile

### ISSUE THREAD

**Issue by misha-dig** [Electrics-Eagles/PiElectricsEagles#25]
You need add file 'config' and write in .cargo path from HOME directory:
Enter command in ternimal: 
1. sudo -s nano ~/.cargo/config
2. Write via nano editor
[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
3. Save and exit

**Comment by alex5250** [comment]
fixed using cross
